name: Český chřest
favicon: null
layout_spectrum: 0.5164628545753658
typography_spectrum: 0.608790151309222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4438153156079352
  lightness: 0.9153817549813539
  saturation: 0.32894854922778904
  rhythmicContrast: 0.9267371227033436
purpose: []
