name: Český chřest
favicon: null
layout_spectrum: 0.52128
typography_spectrum: 0.3776
title: Jediní pěstitelé toho nejlepšího českého chřestu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#999500'
    - '#bbb9ba'
    - '#6a6667'
  brandStrength: 0.625
  lightness: 0.9153817549813539
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
